# This workflow will do a clean install of node dependencies, build the source code and deploy change to gh-pages branch from the build dist/ directory.

name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup NodeJS & Build
        uses: actions/setup-node@v2
        with:
          node-version: '15'
        run: |
          npm ci
          npm run build

      - name: Upload extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: dist/*
