# This workflow will do a clean install of node dependencies, builds the source code and uploads extension artifact.

name: Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - run: npm ci
      - run: npm run build

      - name: Upload extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: dist/*
